# Generated by Django 4.1.5 on 2023-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shope", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kolichestvo",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
