# Generated by Django 4.1.5 on 2023-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shope", "0003_product_kolichestvo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="kolichestvo",
            field=models.PositiveBigIntegerField(),
        ),
    ]
