# Generated by Django 4.1.5 on 2023-05-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shope", "0004_alter_product_kolichestvo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="kolichestvo",
        ),
    ]
