# Generated by Django 4.1.5 on 2023-02-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Phone", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Color",
            new_name="Brands",
        ),
        migrations.RenameModel(
            old_name="Brand",
            new_name="Colors",
        ),
        migrations.RenameModel(
            old_name="Model",
            new_name="Models",
        ),
        migrations.RenameField(
            model_name="brands",
            old_name="color",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="colors",
            old_name="brand",
            new_name="color",
        ),
    ]
