# Generated by Django 4.1.5 on 2023-02-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Phone", "0003_rename_brands_brand_rename_colors_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Phone.brand"
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Phone.color"
            ),
        ),
    ]
