# Generated by Django 4.1.5 on 2023-02-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Phone", "0004_alter_recording_brand_alter_recording_color"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Brand",
            new_name="Brands",
        ),
        migrations.RenameModel(
            old_name="Color",
            new_name="Colors",
        ),
        migrations.RenameModel(
            old_name="Model",
            new_name="Models",
        ),
        migrations.RenameModel(
            old_name="Recording",
            new_name="Recordings",
        ),
    ]
