# Generated by Django 4.2.5 on 2023-09-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Категории",
                "verbose_name_plural": "Категории",
                "ordering": ("model",),
            },
        ),
        migrations.CreateModel(
            name="tripods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("content", models.TextField(blank=True, max_length=1000)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="lens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("type", models.CharField(db_index=True, max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                ("content", models.TextField(blank=True, max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Lens",
                        to="Main.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firm", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("Matrix_format", models.CharField(max_length=30)),
                ("Bayonet", models.CharField(max_length=30)),
                ("lens", models.BooleanField(default=True)),
                ("Image_Stabilizer", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True, max_length=1000)),
                ("image", models.ImageField(upload_to="products/%Y/%m/%d")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Camera",
                        to="Main.category",
                    ),
                ),
            ],
        ),
    ]
