# Generated by Django 4.2.5 on 2023-10-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Binoculars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=30)),
                ("material", models.CharField(db_index=True, max_length=30)),
                ("range", models.CharField(db_index=True, max_length=30)),
                ("content", models.TextField(blank=True, max_length=3000)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stock", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firm", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=50)),
                ("Matrix_format", models.CharField(max_length=30)),
                ("Bayonet", models.CharField(max_length=30)),
                ("lens", models.BooleanField(default=True)),
                ("Image_Stabilizer", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("hand", models.BooleanField(default=False)),
                ("content", models.TextField(blank=True, max_length=1000)),
                ("image", models.ImageField(upload_to="products/%Y/%m/%d")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("stock", models.PositiveBigIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Категории",
                "verbose_name_plural": "Категории",
                "ordering": ("model",),
            },
        ),
        migrations.CreateModel(
            name="Categorys_lighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Charging_time", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Время зарядки",
                "verbose_name_plural": "Время зарядки",
                "ordering": ("Charging_time",),
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="tripods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=10)),
                ("content", models.TextField(blank=True, max_length=1000)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stock", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="lightings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=30)),
                ("power", models.CharField(db_index=True, max_length=200)),
                ("Charging_time", models.CharField(db_index=True, max_length=200)),
                ("content", models.TextField(blank=True, max_length=3000)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stock", models.PositiveBigIntegerField()),
                (
                    "time_power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lighting",
                        to="Main.categorys_lighting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="lens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("type", models.CharField(db_index=True, max_length=200)),
                ("color", models.CharField(max_length=50)),
                ("hand", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                ("content", models.TextField(blank=True, max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stock", models.PositiveBigIntegerField()),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Lens",
                        to="Main.camera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IMG_FILES_TRIPODS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="post_images/", verbose_name="Image"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Main.tripods",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IMG_FILES_LIGHTS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="post_images/", verbose_name="Image"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Main.lightings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IMG_FILES_LENS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="post_images/", verbose_name="Image"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Main.lens",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IMG_FILES_BINOCULARS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="post_images/", verbose_name="Image"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Main.binoculars",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IMG_FILES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="post_images/", verbose_name="Image"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Main.camera",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="camera",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Camera",
                to="Main.category",
            ),
        ),
        migrations.CreateModel(
            name="account_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("key", models.CharField(max_length=30)),
                ("value", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "unique_together": {("username", "key")},
            },
        ),
    ]
