# Generated by Django 4.2.5 on 2023-10-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="color",
        ),
    ]
