# Generated by Django 4.2.5 on 2023-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorys_lighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Charging_time", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Время зарядки",
                "verbose_name_plural": "Время зарядки",
                "ordering": ("Charging_time",),
            },
        ),
    ]
