# Generated by Django 4.2.5 on 2023-09-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_lightings"),
    ]

    operations = [
        migrations.AddField(
            model_name="lightings",
            name="time_power",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="lighting",
                to="Main.categorys_lighting",
            ),
            preserve_default=False,
        ),
    ]
