# Generated by Django 4.2.5 on 2023-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0005_binoculars_alter_lightings_name_alter_tripods_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
