# Generated by Django 4.2.5 on 2023-09-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0006_alter_camera_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="stock",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
