# Generated by Django 4.2.5 on 2023-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0007_camera_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="binoculars",
            name="stock",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lens",
            name="stock",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lightings",
            name="stock",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripods",
            name="stock",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
