# Generated by Django 4.1.5 on 2023-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0002_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zhiguli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("data_added", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Entry",
            new_name="AUDI",
        ),
    ]
