# Generated by Django 4.2.5 on 2023-10-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0009_alter_profile_img_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="text_test",
        ),
    ]
