# Generated by Django 4.2.5 on 2023-10-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lens",
            name="lens",
        ),
        migrations.AlterField(
            model_name="camera",
            name="content",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
