# Generated by Django 4.2.5 on 2023-10-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_remove_lens_lens_alter_camera_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="lens",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="lens",
                to="Main.category",
            ),
            preserve_default=False,
        ),
    ]
