# Generated by Django 4.2.5 on 2023-10-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0006_alter_profile_img_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="text_test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TEXT", models.CharField(max_length=20)),
            ],
        ),
    ]
