# Generated by Django 4.2.5 on 2023-10-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0007_text_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_img",
            name="image",
            field=models.ImageField(
                null=True, upload_to="post_images/", verbose_name="Image"
            ),
        ),
    ]
