# Generated by Django 4.2.5 on 2023-10-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0008_alter_profile_img_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_img",
            name="image",
            field=models.FileField(
                max_length=255,
                null=True,
                upload_to="post_images/",
                verbose_name="Image",
            ),
        ),
    ]
