# Generated by Django 4.1.5 on 2023-02-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FinancesAppCount", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Business",
            new_name="Busines",
        ),
        migrations.RenameModel(
            old_name="Income",
            new_name="Incom",
        ),
        migrations.RenameModel(
            old_name="Month",
            new_name="Mont",
        ),
        migrations.RenameModel(
            old_name="Year",
            new_name="Yea",
        ),
    ]
