# Generated by Django 4.1.5 on 2023-02-12 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "FinancesAppCount",
            "0002_rename_business_busines_rename_income_incom_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Busines",
            new_name="Business",
        ),
        migrations.RenameModel(
            old_name="Incom",
            new_name="Income",
        ),
        migrations.RenameModel(
            old_name="Mont",
            new_name="Month",
        ),
        migrations.RenameModel(
            old_name="Yea",
            new_name="Year",
        ),
    ]
