# Generated by Django 4.1.5 on 2023-02-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0005_alter_price_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="color",
        ),
        migrations.AddField(
            model_name="breed",
            name="color",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="Cats.color",
            ),
            preserve_default=False,
        ),
    ]
