# Generated by Django 4.2.5 on 2023-10-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_rename_product_orderitem_binoculars_orderitem_camera_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
    ]
