# Generated by Django 4.2.5 on 2023-10-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0009_alter_profile_img_image"),
        ("orders", "0008_alter_order_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Binoculars",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_5",
                        to="Main.binoculars",
                    ),
                ),
                (
                    "Camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_1",
                        to="Main.camera",
                    ),
                ),
                (
                    "lens",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_2",
                        to="Main.lens",
                    ),
                ),
                (
                    "lightings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_4",
                        to="Main.lightings",
                    ),
                ),
                (
                    "tripods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_3",
                        to="Main.tripods",
                    ),
                ),
            ],
        ),
    ]
