# Generated by Django 4.2.5 on 2023-10-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_remove_orderitem_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
