# Generated by Django 4.2.5 on 2024-03-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="massage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Massage",
                to="Main.massage",
            ),
        ),
    ]
