# Generated by Django 4.2.5 on 2024-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_orderitem_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
