# Generated by Django 4.1.5 on 2023-03-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0003_menu"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="Men",
        ),
    ]
