# Generated by Django 4.1.5 on 2023-03-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0004_rename_menu_men"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Men",
            new_name="Menu",
        ),
    ]
