# Generated by Django 4.1.5 on 2023-03-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0005_rename_men_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="categ",
        ),
    ]
