# Generated by Django 4.1.5 on 2023-03-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0007_menu_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="owner",
        ),
    ]
