# Generated by Django 4.1.5 on 2023-03-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Food", "0012_menu_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="group",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="group",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
