# Generated by Django 4.1.5 on 2023-03-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Food", "0013_menu_owner_alter_menu_group_alter_restaurant_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="group",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
