# Generated by Django 4.1.5 on 2023-03-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0014_alter_restaurant_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
