# Generated by Django 4.1.5 on 2023-03-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0017_remove_restaurant_categ_remove_restaurant_dish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="group",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="image",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="owner",
        ),
    ]
