# Generated by Django 4.1.5 on 2023-03-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0019_restaurant_categ_restaurant_dish_restaurant_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="categ",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Food.category",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="dish",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
