# Generated by Django 4.1.5 on 2023-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0020_alter_restaurant_categ_alter_restaurant_dish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="imageMenu",
            field=models.ImageField(max_length=255, null=True, upload_to="images/"),
        ),
    ]
