# Generated by Django 4.1.5 on 2023-03-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0022_remove_restaurant_categ_remove_restaurant_dish_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
