# Generated by Django 4.1.5 on 2023-03-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0026_menu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
