# Generated by Django 4.1.5 on 2023-03-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0028_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_restaurant",
                to="Food.restaurant",
            ),
            preserve_default=False,
        ),
    ]
