# Generated by Django 4.1.5 on 2023-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0032_remove_menu_group_remove_menu_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="categ",
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
