# Generated by Django 4.1.5 on 2023-03-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0033_alter_menu_categ_delete_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
