# Generated by Django 4.1.5 on 2023-03-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0034_delete_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categ", models.CharField(max_length=40)),
                ("dish", models.CharField(max_length=10)),
                (
                    "image",
                    models.ImageField(max_length=255, null=True, upload_to="images/"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
