# Generated by Django 4.1.5 on 2023-03-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Food", "0036_menu_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categ", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="menu",
            name="categ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Food.category"
            ),
        ),
    ]
