# Generated by Django 4.1.5 on 2023-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Phone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("data_added", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Xiaomi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("data_added", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
