# Generated by Django 4.2.5 on 2023-10-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_order_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="category",
            new_name="user",
        ),
    ]
