# Generated by Django 4.2.5 on 2023-10-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_email_order_first_name_order_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(max_length=50),
        ),
    ]
