# Generated by Django 4.2.5 on 2023-10-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="Binoculars",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="Camera",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="lens",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="lightings",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="tripods",
        ),
    ]
