# Generated by Django 4.2.5 on 2023-10-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_remove_orderitem_binoculars_remove_orderitem_camera_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="orders.product",
            ),
            preserve_default=False,
        ),
    ]
