# Generated by Django 4.2.5 on 2023-10-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
    ]
