# Generated by Django 4.2.5 on 2023-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
