# Generated by Django 4.2.5 on 2023-10-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
