# Generated by Django 4.1.5 on 2023-01-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FinancesApp", "0002_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("data_added", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FinancesApp.topics",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
            },
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
