# Generated by Django 4.1.5 on 2023-01-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FinancesApp", "0003_entr_delete_entry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entr",
            new_name="Ent",
        ),
        migrations.AlterModelOptions(
            name="ent",
            options={},
        ),
    ]
